name: trigger workflow using api call

on:
  repository_dispatch:
    types: [incident_report]

jobs:
  handle-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Print Incident details
        run: echo "Incident reported"

# to run
#curl -X POST \
# -H "Accept: application/vnd.github+json" \
# -H "Authorization: Bearer YOUR_GITHUB_TOKEN" \
# -H "X-GitHub-Api-Version: 2022-11-28" \
# https://api.github.com/repos/HosamElian/githubActionTraining/dispatches \
# -d '{"event_type": "incident_report", "client_payload": {"message": "Something went wrong", "severity": "high"}}'
